#!/bin/bash

# Guessing json schema
#
# usage: guessjsonschema [file.json]...
# output columns:
#   ! or ?: mandatory or optional
#   count: number of occurrences of a path
#   type: type[,type] | {null,string,boolean,number,array,object}
#   path: path (array indices suppresses)
# using multiple instances as jq input can be handy, eg.:
#   cat "*.json" | guessjsonschema
#   guessjsonschema *.json
# one json array of instances produces an additional root element (array):
#   guessjsonschema arrayOfInstances.json
# two sed commands eliminates and marks with "*" direct recursions (aka.
#   tree structure), not robust! (just delete that two lines)
# last grep shows where to be careful
# TODO
#   aaargh (there has to be a better way)
#   primitive types of array elements (eg.: [str,obj,num...] )
#   detect subtypes (date,int,float,...); common values

jq -rs 'paths as $path  | [
        ( [ $path[] | tostring ] | join(".") ),
        ( getpath($path) | type )
    ] | join(" ")' "$@" |\
awk '{$0 = gensub("(^|\\.)[0-9]+", "[]", "g")} 1' |\
sed -re 's,(\.[^]\[\.]+\[\])\1+,\1,g' |\
awk 'function join(a,t){for(i in a)t=t""(t==""?"":",")""i;return t}
    {
        pathcnt[$1]++
        pathtypecnt[$1][$2]++
    }
    END {
        for (path in pathtypecnt) {
            if (path ~ "]$") continue
            parent = gensub("\\.[^.]*$", "", 1, path)
            printf pathcnt[path]==pathcnt[parent]?"! ":"? "
            printf "%8d %8s %s\n", pathcnt[path], join(pathtypecnt[path]), path
        }
    }' |\
sort -k4 |\
sed -re 's,^(.).(.*(\.[^]\[\.]+)\[\]\3$),\1*\2,' |\
grep --color -E '($|^.\*.*|.*,.*)'
