#!/usr/bin/env bash

# requirements:
# npm init -y && npm install esbuild

function build-editor() {
    npx esbuild src/editor.js --outdir=dist/ --bundle --minify 
}

function build-svg() {
    TEMPLATE=src/lsystem.svg.template
    IN=src/lsystem-svg.js
    OUT=dist/lsystem.svg
    {
        awk '/^HERE/{exit}{print}' $TEMPLATE
        npx esbuild $IN --bundle --format=esm --minify | \
        sed -r 's,(function )([^(]*)(.*)export\{\2 as (.*)\};,\1\4\3,'
        awk 'a{print}/^HERE/{a=1}' $TEMPLATE
    } > $OUT
}

function build-static() {
    cp src/{index.html,editor.css} dist/
    sed -i 's, type="module",,' dist/index.html
}

function main() {
    rm -rf dist && mkdir dist 2>/dev/null || { echo "error:dist"; exit; }
    build-static
    build-editor
    build-svg
    cmp src/lsystem.svg dist/lsystem.svg || echo PlzUpdateSrcSvg
}

main

# TODO node "$(dirname "$0")/build.js" "$@"

